config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|jp/ do
    mount Ckeditor::Engine => '/ckeditor'
    resources :categories
    resources :items
    get 'sessions/new'
    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/dashboard', to: 'static_pages#dashboard'
    get  '/search', to: 'static_pages#search'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get '/auth/:provider/callback', to: 'sessions#create'
    resources :users
  end
  resources :account_activations, only: [:edit]
end

app/models/category.rb
class Category < ApplicationRecord
    # mount_uploader :image_url, AvatarUploader
    has_many :items
    has_one_attached :image_url
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :admin_logged_in, only: [:index, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description,:image_url)
    end

    def admin_logged_in
      unless admin?
        redirect_to :root
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def get_categories
        @categories = Category.all
    end
end

app/views/categories/_form.html.erb
<div class="card mr-5">
  <div class="card-body">
    <%= form_with(model: category, local: true) do |form| %>
      <% if category.errors.any? %>
        <div class="form-group alert au-alert-danger alert-dismissible fade show au-alert au-alert--70per">
          <%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:
          <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="card-title my-3">
          <h3 class="text-left title-2"><%= title %></h3>
      </div>

      <div class="form-group">
        <%= form.label :title, class: "control-label mb-1" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description, class: "control-label mb-1" %>
        <%= form.text_area :description, class: "form-control ckeditor" %>
      </div>
    
  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :image_url, direct_upload: true%>
  </div>

      <button type="submit" class="btn btn-lg btn-info">Submit</button>
      
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    if ($('textarea').length > 0) {
      var data = $('.ckeditor');
      $.each(data, function(i) {
        CKEDITOR.replace(data[i].id)
      });
    }
  });
</script>

app/views/categories/destroy.js.erb
$('.delete-item').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/categories/edit.html.erb
<div class="mt-5 pt-5" style="background-color: #e5e5e5" >
    <div class="row">
        <div class="col-lg-4">
            <%= render 'layouts/sidebar' %> 
        </div>
        <div class="col-lg-8">
            <%= render 'form', category: @category, title: "Edit Category" %>
        </div>

    </div>
    <%= link_to 'Back', items_path, class: "btn btn-lg btn-info text-white" %>
</div>

app/views/categories/index.html.erb
<div class="mt-5 pt-5" style="background-color: #e5e5e5; min-height: 100vh" >
    <div class="row">
        <div class="col-lg-3">
            <%= render 'layouts/sidebar' %> 
        </div>
        <div class="col-lg-9 pl-0">
            <h2 class="mb-4">Categories</h2>
            <div class="row mb-5">
              <div class="col-md-12">
                <div class="table-responsive table-responsive-data2">
                  <table class="table table-data2">
                      <thead>
                        <tr>
                          <th>Title</th>
                          <th>Description</th>
                          <th>Image</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @categories.each do |category| %>
                          <tr>
                            <td><%= category.title %></td>
                            <td><%= raw category.description %></td>
                            <td><%= image_tag category.image_url , width: '52', height: '52' %></td>
                            <td><%= link_to 'Show', category %></td>
                            <td><%= link_to 'Edit', edit_category_path(category) %></td>
                            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, remote: :true, class: "delete-item" %></td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                </div>
              </div>
            </div>
            <%= link_to 'New Category', new_category_path,  class: "btn btn-lg btn-info text-white" %>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<div class="mt-5 pt-5" style="background-color: #e5e5e5" >
    <div class="row">
        <div class="col-lg-4">
            <%= render 'layouts/sidebar' %> 
        </div>
        <div class="col-lg-8">
            <%= render 'form', category: @category, title: "New Category" %>
        </div>

    </div>
    <%= link_to 'Back', items_path, class: "btn btn-lg btn-info text-white" %>
</div>

app/views/categories/show.html.erb
<div class="container mt-5 pt-5">  
  <div class="item-container px-4 pb-5">
    <div class="row">
      <div class="col-md-8">
        <h2><%= @category.title %> - <%= @category.items.count %> recipes</h2>
        <div class="category-info">
          <%= image_tag(@category.image_url, alt: @category.title, width: '170', class: 'my-4 d-inline-block') %>
          <div class="ml-4 d-inline-block"><%= raw @category.description %></div>
        </div>
        
        <div class="py-2" style="border-bottom: 2px solid #dbb34d"><h2><%= @category.title %>の一覧 </h2></div>
        <div class="category-show-all row pt-3">
          <% @category.items.each do |item| %>
            <div class="col-md-4 pb-3">
              <%= link_to image_tag(item.image_url, alt: item.name, width: '100%', height: '100%', class: 'my-4 d-inline-block'), item %>
              <h3><%= link_to item.name, item %></h3>
            </div>
          <% end %>
        </div>
      </div>

      <div class="col-md-4">
        <h3>Relavite items</h3>
        
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>