config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|jp/ do
    mount Ckeditor::Engine => '/ckeditor'
    resources :categories
    resources :items
    get 'sessions/new'
    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/dashboard', to: 'static_pages#dashboard'
    get  '/search', to: 'static_pages#search'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    get '/auth/:provider/callback', to: 'sessions#create'
    resources :users
  end
  resources :account_activations, only: [:edit]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <span class="title"><%= t("home.footer.address") %></span>
        <span>500 Terry Francois Street</span>
        <span>San Francisco, CA 94158</span>
      </div>
      <div class="col-md-3">
        <span class="title"><%= t("home.footer.open") %></span>
        <span><%= t("home.footer.mon") %></span>
        <span><%= t("home.footer.sat") %></span>
      </div>
      <div class="col-md-3">
        <span class="title"><%= t("home.footer.contact") %></span>
        <span>123-456-7890</span>
        <span>info@mysite.com</span>
      </div>
      <div class="col-md-3">
        <span class="title"><%= t("home.footer.follow") %></span>
      </div>
    </div>
    <p>©2019 by Umihara. Proudly created with Wix.com</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- <div id="logo"></div> -->
<nav class="navbar navbar-expand-lg header fixed-top">
  <div class="container">
    <%= form_tag(search_path, :method => "get", class: 'form-inline my-2 my-lg-0') do %>  
      <%= search_field_tag :search, params[:search], placeholder: t("header.search-bar.placeholder"), class: "mb-0 form-control mr-sm-2 " %>   
      <%= button_tag t("header.search-bar.button"), :class => 'btn btn-outline-success my-2 my-sm-0',:name => nil%>  
    <% end %>
    <div class="navbar-collapse" style="margin-right: -5%">
      <ul class="navbar-nav ml-auto">
        
        <li class="nav-item"><%= link_to t("header.item.home") ,   root_path, class: "nav-link header-item" %></li>
        <li class="nav-item"><%= link_to t("header.item.about"),   about_path, class: " nav-link header-item "  %></li>
        <li class="nav-item"><%= link_to t("header.item.contact"),   contact_path, class: " nav-link header-item "  %></li>
        <li class="nav-item dropdown">
            <a href="javascript:" class="dropdown-toggle nav-link header-item" data-toggle="dropdown"><%= t("header.item.menu") %></a>
            <ul class="dropdown-menu">
              <% get_categories.each do |category| %>
                <li><%= link_to category.title, category, class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>

        <% if !logged_in? %>
          <li><%= link_to t("header.item.login"), login_path, class: "nav-link header-item"  %></li>

        <% elsif current_user.admin? %>
          <li class="dropdown">
            <a href="javascript:" class="dropdown-toggle nav-link header-item" data-toggle="dropdown">
              <%= t("header.item.account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item"><%= link_to t("header.login-dropdown.profile"), user_path(current_user), class: "dropdown-item" %></li>
              <li class="nav-item"><%= link_to t("header.login-dropdown.settings"), edit_user_path(current_user), class: "dropdown-item"  %></li>
              <li class="nav-item"><%= link_to t("header.login-dropdown.dashboard"), dashboard_path, class: "dropdown-item" %></li>
              <div class="dropdown-divider"></div>
              <li class="nav-item">
                <%= link_to t("header.login-dropdown.logout"), logout_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>

        <% elsif logged_in? %>
          <li class="dropdown">
            <a href="javascript:" class="dropdown-toggle nav-link header-item" data-toggle="dropdown">
              <%= t("header.item.account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item"><%= link_to t("header.login-dropdown.profile"), user_path(current_user), class: "dropdown-item" %></li>
              <li class="nav-item"><%= link_to t("header.login-dropdown.settings"), edit_user_path(current_user), class: "dropdown-item"  %></li>
              <div class="dropdown-divider"></div>
              <li class="nav-item">
                <%= link_to t("header.login-dropdown.logout"), logout_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>

        <% end %>

        <li class="dropdown">
          <a href="javascript:" class="dropdown-toggle nav-link header-item" data-toggle="dropdown">
            <% if I18n.locale == :en %>
              <%= t("header.item.language.en") %>
            <% else %>
              <%= t("header.item.language.jp") %>
            <% end %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" style="min-width: 90px">
            <li class="nav-item"><%= link_to "English", locale:"en" %></li>
            <li class="nav-item"><%= link_to "日本語", locale:"jp"  %></li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<!-- END MENU SIDEBAR-->
<aside class="menu-sidebar d-none d-lg-block">
    <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
            <ul class="list-unstyled navbar__list">
                <li>
                    <%= link_to "Items", items_path %>
                </li>
                <li>
                    <%= link_to "Categories", categories_path %>
                </li>
                <li>
                    <%= link_to "Users", users_path %>
                </li>
                <li>
                    <a href="#">Maps</a>
                </li>
            </ul>
        </nav>
    </div>
</aside>
<!-- END MENU SIDEBAR-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <script src="//maps.google.com/maps/api/js?key=AIzaSyB5pt7VFBt5GKxBnTCS_0raFHybw8Zfzvk"></script> 
    <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
    <script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script> 
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>  
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

  </body>
</html>